# Generated by Django 3.1.3 on 2020-11-16 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField()),
                ('item', models.CharField(max_length=40)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('item_count', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('cost', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(max_length=254)),
                ('long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('owner', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
